name: Build Inspector Gadget container and push to Docker Hub

on:
  push:
    paths:
    - ./WebApp/

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Registry
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build Docker Image (Linux)
      run: docker build --no-cache -t jelledruyts/inspectorgadget:latest ./WebApp
    - name: Push Docker Image to Registry (Linux)
      env:
        DOCKER_REGISTRY_URL: jelledruyts
        CONTAINER_IMAGE_NAME: inspectorgadget
      run: docker push jelledruyts/inspectorgadget:latest
    - name: Build Docker Image (Windows)
      run: docker build --no-cache -t jelledruyts/inspectorgadget:latest-nanoserver -f ./WebApp/Dockerfile-Nanoserver ./WebApp
    - name: Push Docker Image to Registry (Windows)
      env:
        DOCKER_REGISTRY_URL: jelledruyts
        CONTAINER_IMAGE_NAME: inspectorgadget
      run: docker push jelledruyts/inspectorgadget:latest-nanoserver
