name: Build Inspector Gadget container and push to Docker Hub

on:
  push:
    branches:
    - master
    paths:
    - 'WebApp/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
    - name: Docker Hub login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image (Linux)
      run: docker build --no-cache --build-arg app_version=1.0.${env:GITHUB_RUN_NUMBER} --build-arg source_version=${env:GITHUB_SHA} -t jelledruyts/inspectorgadget:latest -f ./WebApp/Linux.Dockerfile ./WebApp
    - name: Push Docker Image to Registry (Linux)
      run: docker push jelledruyts/inspectorgadget:latest
    - name: Build Docker Image (Windows)
      run: docker build --no-cache --build-arg app_version=1.0.${env:GITHUB_RUN_NUMBER} --build-arg source_version=${env:GITHUB_SHA} -t jelledruyts/inspectorgadget:latest-windows -f ./WebApp/Windows.Dockerfile ./WebApp
    - name: Push Docker Image to Registry (Windows)
      run: docker push jelledruyts/inspectorgadget:latest-windows
