name: Build Inspector Gadget container and push to Docker Hub

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Registry
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - name: Build Docker Image
      run: docker build --no-cache -t jelledruyts/inspectorgadget:latest ./WebApp
    - name: Push Docker Image to Registry
      env:
        DOCKER_REGISTRY_URL: jelledruyts
        CONTAINER_IMAGE_NAME: inspectorgadget
      run: docker push jelledruyts/inspectorgadget:latest
